# http://docs.travis-ci.com/user/languages/ruby/
language: ruby
sudo: false
rvm:
  - 2.4
  - jruby-head
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
cache: bundler
before_install:
  - gem install bundler # for jruby-head
  - gem update bundler
